const king = '<div class="piece" id="king"><i class="fa-solid fa-chess-king"></i></div>'
const queen = '<div class="piece" id="queen"><i class="fa-solid fa-chess-queen"></i></div>'
const knight = '<div class="piece" id="knight"><i class="fa-solid fa-chess-knight"></i></div>'
const bishop = '<div class="piece" id="bishop"><i class="fa-solid fa-chess-bishop"></i></div>'
const rook = '<div class="piece" id="rook"><i class="fa-solid fa-chess-rook"></i></div>'
const pawn = '<div class="piece" id="pawn"><i class="fa-solid fa-chess-pawn"></i></div>'
